import type { AdvancedBrandingTheme } from '../types/brandingAdvanced';

export const advancedBrandingPresets: AdvancedBrandingTheme[] = [
  {
    id: 'modern-pro',
    name: 'Modern Pro',
    description: 'Contemporary, clean, professional design system',
    category: 'modern',
    colors: {
      primary: '#1F2937',
      primaryLight: '#F3F4F6',
      primaryDark: '#111827',
      secondary: '#3B82F6',
      accent: '#06B6D4',
      accentLight: '#CFFAFE',
      neutral50: '#F9FAFB',
      neutral100: '#F3F4F6',
      neutral200: '#E5E7EB',
      neutral300: '#D1D5DB',
      neutral400: '#9CA3AF',
      neutral500: '#6B7280',
      neutral600: '#4B5563',
      neutral700: '#374151',
      neutral800: '#1F2937',
      neutral900: '#111827',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
    typography: {
      fontFamily: {
        sans: '"Inter", "Helvetica Neue", sans-serif',
        serif: '"Merriweather", serif',
        mono: '"Fira Code", monospace',
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      sizes: {
        xs: { size: '12px', lineHeight: '16px' },
        sm: { size: '14px', lineHeight: '20px' },
        base: { size: '16px', lineHeight: '24px' },
        lg: { size: '18px', lineHeight: '28px' },
        xl: { size: '20px', lineHeight: '28px' },
        '2xl': { size: '24px', lineHeight: '32px' },
        '3xl': { size: '30px', lineHeight: '36px' },
        '4xl': { size: '36px', lineHeight: '40px' },
        '5xl': { size: '48px', lineHeight: '48px' },
      },
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '32px',
      '2xl': '48px',
      '3xl': '64px',
      '4xl': '96px',
    },
    borderRadius: {
      none: '0',
      sm: '4px',
      base: '6px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      full: '9999px',
    },
    shadow: {
      none: 'none',
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      base: '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    },
    animation: {
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      timing: {
        ease: 'ease',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
      keyframes: {
        fadeIn: 'fade 300ms ease-in',
        slideUp: 'slide-up 300ms ease-out',
        bounce: 'bounce 1s infinite',
      },
    },
    button: {
      size: {
        xs: { padding: '4px 8px', fontSize: '12px' },
        sm: { padding: '8px 12px', fontSize: '14px' },
        md: { padding: '10px 16px', fontSize: '16px' },
        lg: { padding: '12px 24px', fontSize: '18px' },
        xl: { padding: '14px 32px', fontSize: '20px' },
      },
      variant: {
        solid: { bg: '#1F2937', text: '#FFFFFF', hover: '#111827' },
        outline: { border: '#E5E7EB', text: '#1F2937', hover: '#F3F4F6' },
        ghost: { bg: 'transparent', text: '#1F2937', hover: '#F3F4F6' },
      },
      radius: '8px',
      fontWeight: '600',
    },
    card: {
      layout: 'grid',
      imagePosition: 'top',
      imageHeight: '200px',
      imageWidth: '100%',
      textAlignment: 'left',
      shadow: 'md',
      borderRadius: '12px',
      padding: '16px',
      gap: '12px',
      hoverEffect: 'lift',
    },
    navigation: {
      background: '#FFFFFF',
      text: '#1F2937',
      activeTab: '#1F2937',
      inactiveButton: '#F3F4F6',
      hoverColor: '#E5E7EB',
      borderRadius: '8px',
      buttonSize: 'md',
      alignment: 'center',
      position: 'sticky',
      themeMode: 'light',
      transparency: 'none',
      shadow: true,
    },
    form: {
      inputBg: '#F9FAFB',
      inputBorder: '#E5E7EB',
      inputText: '#1F2937',
      inputPlaceholder: '#9CA3AF',
      labelText: '#374151',
      errorColor: '#EF4444',
      successColor: '#10B981',
      borderRadius: '8px',
      focusRing: '#3B82F6',
      shadow: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    preview: {
      thumbnail: 'https://via.placeholder.com/200x150?text=Modern+Pro',
      colors: ['#1F2937', '#3B82F6', '#06B6D4', '#10B981'],
    },
  },
  {
    id: 'luxury-elite',
    name: 'Luxury Elite',
    description: 'Premium, sophisticated, high-end aesthetic',
    category: 'luxury',
    colors: {
      primary: '#1A1410',
      primaryLight: '#F5EBE0',
      primaryDark: '#0F0A08',
      secondary: '#D4AF37',
      accent: '#C41E3A',
      accentLight: '#F4CCCC',
      neutral50: '#FEFCF9',
      neutral100: '#F5EBE0',
      neutral200: '#EBD5C1',
      neutral300: '#DCC4A8',
      neutral400: '#C9B08F',
      neutral500: '#A89B7D',
      neutral600: '#8B8367',
      neutral700: '#6E6B63',
      neutral800: '#484038',
      neutral900: '#2C2620',
      success: '#2D5016',
      warning: '#B8860B',
      error: '#8B0000',
      info: '#4169E1',
    },
    typography: {
      fontFamily: {
        sans: '"Playfair Display", serif',
        serif: '"Lora", serif',
        mono: '"IBM Plex Mono", monospace',
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      sizes: {
        xs: { size: '13px', lineHeight: '18px' },
        sm: { size: '15px', lineHeight: '22px' },
        base: { size: '18px', lineHeight: '26px' },
        lg: { size: '20px', lineHeight: '30px' },
        xl: { size: '24px', lineHeight: '32px' },
        '2xl': { size: '32px', lineHeight: '40px' },
        '3xl': { size: '40px', lineHeight: '48px' },
        '4xl': { size: '48px', lineHeight: '56px' },
        '5xl': { size: '60px', lineHeight: '66px' },
      },
    },
    spacing: {
      xs: '6px',
      sm: '12px',
      md: '20px',
      lg: '32px',
      xl: '48px',
      '2xl': '64px',
      '3xl': '96px',
      '4xl': '128px',
    },
    borderRadius: {
      none: '0',
      sm: '2px',
      base: '4px',
      md: '6px',
      lg: '10px',
      xl: '16px',
      full: '9999px',
    },
    shadow: {
      none: 'none',
      sm: '0 2px 4px rgba(0, 0, 0, 0.1)',
      base: '0 4px 8px rgba(0, 0, 0, 0.15)',
      md: '0 8px 16px rgba(0, 0, 0, 0.2)',
      lg: '0 16px 32px rgba(0, 0, 0, 0.25)',
      xl: '0 24px 48px rgba(0, 0, 0, 0.3)',
      '2xl': '0 32px 64px rgba(0, 0, 0, 0.35)',
    },
    animation: {
      duration: {
        fast: '200ms',
        normal: '400ms',
        slow: '600ms',
      },
      timing: {
        ease: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        fadeIn: 'fade 400ms cubic-bezier(0.4, 0, 0.2, 1)',
        slideDown: 'slide-down 400ms cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
    button: {
      size: {
        xs: { padding: '8px 12px', fontSize: '13px' },
        sm: { padding: '10px 16px', fontSize: '14px' },
        md: { padding: '12px 24px', fontSize: '16px' },
        lg: { padding: '14px 32px', fontSize: '18px' },
        xl: { padding: '16px 40px', fontSize: '20px' },
      },
      variant: {
        solid: { bg: '#D4AF37', text: '#1A1410', hover: '#C99F2A' },
        outline: { border: '#D4AF37', text: '#D4AF37', hover: 'transparent' },
        ghost: { bg: 'transparent', text: '#D4AF37', hover: '#F5EBE0' },
      },
      radius: '4px',
      fontWeight: '600',
    },
    card: {
      layout: 'grid',
      imagePosition: 'top',
      imageHeight: '240px',
      imageWidth: '100%',
      textAlignment: 'center',
      shadow: 'lg',
      borderRadius: '8px',
      padding: '24px',
      gap: '16px',
      hoverEffect: 'glow',
    },
    navigation: {
      background: '#1A1410',
      text: '#F5EBE0',
      activeTab: '#D4AF37',
      inactiveButton: '#484038',
      hoverColor: '#6E6B63',
      borderRadius: '0',
      buttonSize: 'md',
      alignment: 'center',
      position: 'fixed',
      themeMode: 'dark',
      transparency: 'medium',
      shadow: true,
    },
    form: {
      inputBg: '#FEFCF9',
      inputBorder: '#EBD5C1',
      inputText: '#1A1410',
      inputPlaceholder: '#A89B7D',
      labelText: '#6E6B63',
      errorColor: '#8B0000',
      successColor: '#2D5016',
      borderRadius: '4px',
      focusRing: '#D4AF37',
      shadow: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    preview: {
      thumbnail: 'https://via.placeholder.com/200x150?text=Luxury+Elite',
      colors: ['#1A1410', '#D4AF37', '#C41E3A', '#F5EBE0'],
    },
  },
  {
    id: 'minimal-zen',
    name: 'Minimal Zen',
    description: 'Simple, calm, minimalist aesthetic',
    category: 'minimal',
    colors: {
      primary: '#FFFFFF',
      primaryLight: '#F8F8F8',
      primaryDark: '#000000',
      secondary: '#000000',
      accent: '#808080',
      accentLight: '#D3D3D3',
      neutral50: '#FAFAFA',
      neutral100: '#F5F5F5',
      neutral200: '#EEEEEE',
      neutral300: '#E0E0E0',
      neutral400: '#BDBDBD',
      neutral500: '#9E9E9E',
      neutral600: '#757575',
      neutral700: '#616161',
      neutral800: '#424242',
      neutral900: '#212121',
      success: '#66BB6A',
      warning: '#FFA726',
      error: '#EF5350',
      info: '#42A5F5',
    },
    typography: {
      fontFamily: {
        sans: '"Segoe UI", "Roboto", sans-serif',
        serif: '"Georgia", serif',
        mono: '"Courier New", monospace',
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      sizes: {
        xs: { size: '11px', lineHeight: '14px' },
        sm: { size: '13px', lineHeight: '18px' },
        base: { size: '15px', lineHeight: '22px' },
        lg: { size: '17px', lineHeight: '26px' },
        xl: { size: '19px', lineHeight: '28px' },
        '2xl': { size: '22px', lineHeight: '32px' },
        '3xl': { size: '28px', lineHeight: '36px' },
        '4xl': { size: '34px', lineHeight: '40px' },
        '5xl': { size: '44px', lineHeight: '48px' },
      },
    },
    spacing: {
      xs: '2px',
      sm: '4px',
      md: '8px',
      lg: '16px',
      xl: '24px',
      '2xl': '32px',
      '3xl': '48px',
      '4xl': '64px',
    },
    borderRadius: {
      none: '0',
      sm: '2px',
      base: '3px',
      md: '4px',
      lg: '6px',
      xl: '8px',
      full: '9999px',
    },
    shadow: {
      none: 'none',
      sm: '0 1px 1px rgba(0, 0, 0, 0.03)',
      base: '0 1px 2px rgba(0, 0, 0, 0.05)',
      md: '0 2px 4px rgba(0, 0, 0, 0.08)',
      lg: '0 4px 8px rgba(0, 0, 0, 0.1)',
      xl: '0 8px 16px rgba(0, 0, 0, 0.12)',
      '2xl': '0 12px 24px rgba(0, 0, 0, 0.15)',
    },
    animation: {
      duration: {
        fast: '100ms',
        normal: '200ms',
        slow: '300ms',
      },
      timing: {
        ease: 'linear',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
      keyframes: {
        fadeIn: 'fade 200ms linear',
        slideIn: 'slide 200ms ease-out',
      },
    },
    button: {
      size: {
        xs: { padding: '4px 8px', fontSize: '11px' },
        sm: { padding: '6px 10px', fontSize: '12px' },
        md: { padding: '8px 12px', fontSize: '13px' },
        lg: { padding: '10px 16px', fontSize: '14px' },
        xl: { padding: '12px 20px', fontSize: '15px' },
      },
      variant: {
        solid: { bg: '#000000', text: '#FFFFFF', hover: '#212121' },
        outline: { border: '#000000', text: '#000000', hover: '#F5F5F5' },
        ghost: { bg: 'transparent', text: '#000000', hover: '#FAFAFA' },
      },
      radius: '2px',
      fontWeight: '500',
    },
    card: {
      layout: 'grid',
      imagePosition: 'top',
      imageHeight: '180px',
      imageWidth: '100%',
      textAlignment: 'center',
      shadow: 'none',
      borderRadius: '2px',
      padding: '12px',
      gap: '8px',
      hoverEffect: 'scale',
    },
    navigation: {
      background: '#FFFFFF',
      text: '#000000',
      activeTab: '#000000',
      inactiveButton: '#F5F5F5',
      hoverColor: '#EEEEEE',
      borderRadius: '0',
      buttonSize: 'sm',
      alignment: 'center',
      position: 'sticky',
      themeMode: 'light',
      transparency: 'none',
      shadow: false,
    },
    form: {
      inputBg: '#F8F8F8',
      inputBorder: '#EEEEEE',
      inputText: '#000000',
      inputPlaceholder: '#9E9E9E',
      labelText: '#424242',
      errorColor: '#EF5350',
      successColor: '#66BB6A',
      borderRadius: '2px',
      focusRing: '#000000',
      shadow: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    preview: {
      thumbnail: 'https://via.placeholder.com/200x150?text=Minimal+Zen',
      colors: ['#FFFFFF', '#000000', '#808080', '#F5F5F5'],
    },
  },
  {
    id: 'bold-energy',
    name: 'Bold Energy',
    description: 'Vibrant, energetic, attention-grabbing',
    category: 'bold',
    colors: {
      primary: '#FF2D55',
      primaryLight: '#FFE1E9',
      primaryDark: '#CC0033',
      secondary: '#00D9FF',
      accent: '#FFED4E',
      accentLight: '#FFFFF0',
      neutral50: '#F5F5F5',
      neutral100: '#ECECEC',
      neutral200: '#D9D9D9',
      neutral300: '#CCCCCC',
      neutral400: '#999999',
      neutral500: '#666666',
      neutral600: '#333333',
      neutral700: '#1A1A1A',
      neutral800: '#0D0D0D',
      neutral900: '#000000',
      success: '#00D97F',
      warning: '#FF9F1A',
      error: '#FF2D55',
      info: '#00D9FF',
    },
    typography: {
      fontFamily: {
        sans: '"Poppins", sans-serif',
        serif: '"Space Mono", monospace',
        mono: '"IBM Plex Mono", monospace',
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      sizes: {
        xs: { size: '12px', lineHeight: '16px' },
        sm: { size: '14px', lineHeight: '20px' },
        base: { size: '16px', lineHeight: '24px' },
        lg: { size: '18px', lineHeight: '28px' },
        xl: { size: '22px', lineHeight: '28px' },
        '2xl': { size: '28px', lineHeight: '36px' },
        '3xl': { size: '36px', lineHeight: '44px' },
        '4xl': { size: '48px', lineHeight: '56px' },
        '5xl': { size: '60px', lineHeight: '68px' },
      },
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '12px',
      lg: '20px',
      xl: '32px',
      '2xl': '48px',
      '3xl': '64px',
      '4xl': '96px',
    },
    borderRadius: {
      none: '0',
      sm: '8px',
      base: '10px',
      md: '12px',
      lg: '16px',
      xl: '24px',
      full: '9999px',
    },
    shadow: {
      none: 'none',
      sm: '0 2px 8px rgba(255, 45, 85, 0.15)',
      base: '0 4px 12px rgba(255, 45, 85, 0.2)',
      md: '0 8px 24px rgba(255, 45, 85, 0.25)',
      lg: '0 12px 32px rgba(255, 45, 85, 0.3)',
      xl: '0 16px 48px rgba(255, 45, 85, 0.35)',
      '2xl': '0 20px 64px rgba(255, 45, 85, 0.4)',
    },
    animation: {
      duration: {
        fast: '100ms',
        normal: '250ms',
        slow: '400ms',
      },
      timing: {
        ease: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        easeIn: 'cubic-bezier(0.45, 0, 1, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.55, 1.2)',
        easeInOut: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        bounce: 'bounce 600ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        pulse: 'pulse 2s ease-in-out infinite',
      },
    },
    button: {
      size: {
        xs: { padding: '6px 12px', fontSize: '12px' },
        sm: { padding: '8px 14px', fontSize: '13px' },
        md: { padding: '10px 20px', fontSize: '14px' },
        lg: { padding: '12px 28px', fontSize: '16px' },
        xl: { padding: '14px 36px', fontSize: '18px' },
      },
      variant: {
        solid: { bg: '#FF2D55', text: '#FFFFFF', hover: '#CC0033' },
        outline: { border: '#FF2D55', text: '#FF2D55', hover: '#FFE1E9' },
        ghost: { bg: 'transparent', text: '#FF2D55', hover: '#FFE1E9' },
      },
      radius: '12px',
      fontWeight: '700',
    },
    card: {
      layout: 'grid',
      imagePosition: 'top',
      imageHeight: '200px',
      imageWidth: '100%',
      textAlignment: 'left',
      shadow: 'md',
      borderRadius: '16px',
      padding: '16px',
      gap: '12px',
      hoverEffect: 'lift',
    },
    navigation: {
      background: '#FFFFFF',
      text: '#1A1A1A',
      activeTab: '#FF2D55',
      inactiveButton: '#F5F5F5',
      hoverColor: '#FFE1E9',
      borderRadius: '12px',
      buttonSize: 'md',
      alignment: 'center',
      position: 'sticky',
      themeMode: 'light',
      transparency: 'low',
      shadow: true,
    },
    form: {
      inputBg: '#FAFAFA',
      inputBorder: '#FF2D55',
      inputText: '#1A1A1A',
      inputPlaceholder: '#999999',
      labelText: '#333333',
      errorColor: '#FF2D55',
      successColor: '#00D97F',
      borderRadius: '8px',
      focusRing: '#FF2D55',
      shadow: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    preview: {
      thumbnail: 'https://via.placeholder.com/200x150?text=Bold+Energy',
      colors: ['#FF2D55', '#00D9FF', '#FFED4E', '#1A1A1A'],
    },
  },
  {
    id: 'playful-kids',
    name: 'Playful Kids',
    description: 'Fun, colorful, child-friendly design',
    category: 'playful',
    colors: {
      primary: '#FF6B6B',
      primaryLight: '#FFE5E5',
      primaryDark: '#CC4444',
      secondary: '#4ECDC4',
      accent: '#FFE66D',
      accentLight: '#FFFACD',
      neutral50: '#F9F9F9',
      neutral100: '#F0F0F0',
      neutral200: '#E0E0E0',
      neutral300: '#CCCCCC',
      neutral400: '#999999',
      neutral500: '#666666',
      neutral600: '#444444',
      neutral700: '#222222',
      neutral800: '#111111',
      neutral900: '#000000',
      success: '#51CF66',
      warning: '#FFA94D',
      error: '#FF6B6B',
      info: '#74C0FC',
    },
    typography: {
      fontFamily: {
        sans: '"Fredoka", sans-serif',
        serif: '"Bubblegum Sans", cursive',
        mono: '"Inconsolata", monospace',
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      sizes: {
        xs: { size: '12px', lineHeight: '16px' },
        sm: { size: '14px', lineHeight: '20px' },
        base: { size: '16px', lineHeight: '24px' },
        lg: { size: '18px', lineHeight: '28px' },
        xl: { size: '20px', lineHeight: '28px' },
        '2xl': { size: '26px', lineHeight: '34px' },
        '3xl': { size: '32px', lineHeight: '40px' },
        '4xl': { size: '40px', lineHeight: '48px' },
        '5xl': { size: '52px', lineHeight: '60px' },
      },
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
      '2xl': '32px',
      '3xl': '48px',
      '4xl': '64px',
    },
    borderRadius: {
      none: '0',
      sm: '12px',
      base: '16px',
      md: '20px',
      lg: '24px',
      xl: '32px',
      full: '9999px',
    },
    shadow: {
      none: 'none',
      sm: '0 2px 4px rgba(255, 107, 107, 0.1)',
      base: '0 4px 8px rgba(255, 107, 107, 0.15)',
      md: '0 8px 16px rgba(255, 107, 107, 0.2)',
      lg: '0 12px 24px rgba(255, 107, 107, 0.25)',
      xl: '0 16px 32px rgba(255, 107, 107, 0.3)',
      '2xl': '0 20px 40px rgba(255, 107, 107, 0.35)',
    },
    animation: {
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      timing: {
        ease: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
      keyframes: {
        wiggle: 'wiggle 600ms ease-in-out infinite',
        bounce: 'bounce 800ms ease-in-out infinite',
      },
    },
    button: {
      size: {
        xs: { padding: '6px 12px', fontSize: '12px' },
        sm: { padding: '8px 14px', fontSize: '13px' },
        md: { padding: '10px 20px', fontSize: '14px' },
        lg: { padding: '12px 28px', fontSize: '16px' },
        xl: { padding: '14px 36px', fontSize: '18px' },
      },
      variant: {
        solid: { bg: '#FF6B6B', text: '#FFFFFF', hover: '#CC4444' },
        outline: { border: '#FF6B6B', text: '#FF6B6B', hover: '#FFE5E5' },
        ghost: { bg: 'transparent', text: '#FF6B6B', hover: '#FFE5E5' },
      },
      radius: '20px',
      fontWeight: '600',
    },
    card: {
      layout: 'grid',
      imagePosition: 'top',
      imageHeight: '180px',
      imageWidth: '100%',
      textAlignment: 'center',
      shadow: 'base',
      borderRadius: '24px',
      padding: '14px',
      gap: '10px',
      hoverEffect: 'bounce',
    },
    navigation: {
      background: '#FFFFFF',
      text: '#222222',
      activeTab: '#FF6B6B',
      inactiveButton: '#F0F0F0',
      hoverColor: '#FFE5E5',
      borderRadius: '20px',
      buttonSize: 'md',
      alignment: 'center',
      position: 'sticky',
      themeMode: 'light',
      transparency: 'low',
      shadow: true,
    },
    form: {
      inputBg: '#F9F9F9',
      inputBorder: '#FFE5E5',
      inputText: '#222222',
      inputPlaceholder: '#999999',
      labelText: '#444444',
      errorColor: '#FF6B6B',
      successColor: '#51CF66',
      borderRadius: '16px',
      focusRing: '#FF6B6B',
      shadow: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    preview: {
      thumbnail: 'https://via.placeholder.com/200x150?text=Playful+Kids',
      colors: ['#FF6B6B', '#4ECDC4', '#FFE66D', '#74C0FC'],
    },
  },
  {
    id: 'classic-heritage',
    name: 'Classic Heritage',
    description: 'Traditional, timeless, heritage brand',
    category: 'classic',
    colors: {
      primary: '#8B4513',
      primaryLight: '#D2B48C',
      primaryDark: '#3E2723',
      secondary: '#654321',
      accent: '#CD853F',
      accentLight: '#F5DEB3',
      neutral50: '#FFFAF0',
      neutral100: '#FFEFD5',
      neutral200: '#FFDEAD',
      neutral300: '#FFCB96',
      neutral400: '#E6B87D',
      neutral500: '#CCA464',
      neutral600: '#A0826D',
      neutral700: '#70563D',
      neutral800: '#3E2723',
      neutral900: '#1A1410',
      success: '#6B8E23',
      warning: '#DAA520',
      error: '#8B0000',
      info: '#4169E1',
    },
    typography: {
      fontFamily: {
        sans: '"Georgia", serif',
        serif: '"Garamond", serif',
        mono: '"Courier New", monospace',
      },
      fontWeight: {
        thin: 100,
        extralight: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      sizes: {
        xs: { size: '13px', lineHeight: '18px' },
        sm: { size: '15px', lineHeight: '21px' },
        base: { size: '17px', lineHeight: '26px' },
        lg: { size: '19px', lineHeight: '28px' },
        xl: { size: '22px', lineHeight: '32px' },
        '2xl': { size: '28px', lineHeight: '36px' },
        '3xl': { size: '36px', lineHeight: '44px' },
        '4xl': { size: '44px', lineHeight: '52px' },
        '5xl': { size: '56px', lineHeight: '64px' },
      },
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '32px',
      '2xl': '48px',
      '3xl': '64px',
      '4xl': '96px',
    },
    borderRadius: {
      none: '0',
      sm: '2px',
      base: '4px',
      md: '6px',
      lg: '8px',
      xl: '12px',
      full: '9999px',
    },
    shadow: {
      none: 'none',
      sm: '0 1px 3px rgba(139, 69, 19, 0.1)',
      base: '0 2px 6px rgba(139, 69, 19, 0.15)',
      md: '0 4px 12px rgba(139, 69, 19, 0.2)',
      lg: '0 8px 20px rgba(139, 69, 19, 0.25)',
      xl: '0 12px 30px rgba(139, 69, 19, 0.3)',
      '2xl': '0 16px 40px rgba(139, 69, 19, 0.35)',
    },
    animation: {
      duration: {
        fast: '200ms',
        normal: '400ms',
        slow: '600ms',
      },
      timing: {
        ease: 'ease',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
      keyframes: {
        fadeIn: 'fade 400ms ease-in-out',
        slideDown: 'slide-down 400ms ease-out',
      },
    },
    button: {
      size: {
        xs: { padding: '6px 12px', fontSize: '13px' },
        sm: { padding: '8px 14px', fontSize: '14px' },
        md: { padding: '10px 20px', fontSize: '15px' },
        lg: { padding: '12px 28px', fontSize: '17px' },
        xl: { padding: '14px 36px', fontSize: '19px' },
      },
      variant: {
        solid: { bg: '#8B4513', text: '#FFFAF0', hover: '#654321' },
        outline: { border: '#8B4513', text: '#8B4513', hover: '#FFEFD5' },
        ghost: { bg: 'transparent', text: '#8B4513', hover: '#FFEFD5' },
      },
      radius: '4px',
      fontWeight: '600',
    },
    card: {
      layout: 'list',
      imagePosition: 'left',
      imageHeight: '160px',
      imageWidth: '160px',
      textAlignment: 'left',
      shadow: 'md',
      borderRadius: '6px',
      padding: '16px',
      gap: '16px',
      hoverEffect: 'scale',
    },
    navigation: {
      background: '#FFFAF0',
      text: '#3E2723',
      activeTab: '#8B4513',
      inactiveButton: '#FFEFD5',
      hoverColor: '#FFDEAD',
      borderRadius: '4px',
      buttonSize: 'md',
      alignment: 'left',
      position: 'relative',
      themeMode: 'light',
      transparency: 'none',
      shadow: false,
    },
    form: {
      inputBg: '#FFFAF0',
      inputBorder: '#D2B48C',
      inputText: '#3E2723',
      inputPlaceholder: '#A0826D',
      labelText: '#654321',
      errorColor: '#8B0000',
      successColor: '#6B8E23',
      borderRadius: '4px',
      focusRing: '#8B4513',
      shadow: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    preview: {
      thumbnail: 'https://via.placeholder.com/200x150?text=Classic+Heritage',
      colors: ['#8B4513', '#D2B48C', '#CD853F', '#3E2723'],
    },
  },
];
